---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - "App Store"
  - Music
  - Messages
  - FaceTime
  - Contacts
  - Maps
  - Notes
  - Reminders
  - Photos
  - Siri
dockitems_persist:
  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app/"
    pos: 0
  - name: "Todoist"
    path: "/Applications/Todoist.app/"
    pos: 1
  - name: "Obsidian"
    path: "/Applications/Obsidian.app/"
    pos: 2
  - name: "Kitty"
    path: "/Applications/kitty.app/"
    pos: 3
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: git@github.com:clempat/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/workspace/perso/dotfiles
dotfiles_repo_version: main
dotfiles_files:
  - .zprofile
  - .zshrc
  - .osx
  - .bashrc
  - .p10k.zsh
  - .profile
  - .tmux.conf
  - .tmux-cht-command
  - .tmux-cht-languages
  - .config/nvim
  - .local/bin/tmux-sessionizer
  - .gitconfig
  - .config/systemd
  - .config/kitty
  - .config/i3
  - .config/i3status
  - .config/picom
  - .config/rofi
  - .config/dunst
  - .config/fontconfig
  - .local/share/rofi
  - .config/gtk-3.0/settings.ini
  - .config/gtk-2.0/settings.ini

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ripgrep
  - autoconf
  - bash-completion
  - git
  - github/gh/gh
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - cowsay
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - zsh
  - wget
  - antigen
  - { name: luajit, state: head }
  - { name: neovim, state: head }
  - tmux
  - fzf
  - jenv

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - nextcloud
  - 1password
  - chromedriver
  - docker
  - dropbox
  - firefox-developer-edition
  - google-chrome
  - brave-browser
  - handbrake
  - licecap
  - sequel-ace
  - slack
  - transmit
  - alfred
  - discord
  - caffeine
  - brewcake
  - amethyst
  - kitty

homebrew_cask_uninstalled_apps: []

# See `geerlingguy.mas` role documentation for usage instructions.
# Looks like login does not works any more: https://github.com/mas-cli/mas/issues/164
mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
  - { id: 585829637, name: "Todoist" }
  - { id: 967805235, name: "Paste" }
  - { id: 419330170, name: "Moom" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: tldr
  - name: typescript
  - name: pnpm
  - name: yarn
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

powerline_fonts:
  - RobotoMono

apt_packages:
  - dconf-cli
  - i3-gaps
  - pavucontrol
  - moreutils
  - dconf-editor
  - golang
  - python3-pip
  - tmux
  - wireshark
  - fzf
  - xclip
  - screenkey
  - ripgrep

pacman_packages:
  - i3-gaps
  - bluez
  - bluez-utils
  - blueman
  - xorg-server
  - xorg-apps
  - xorg-xinit
  - lightdm
  - lightdm-gtk-greeter
  - ttf-ubuntu-font-family
  - ttf-dejavu
  - ttf-freefont
  - pavucontrol
  - moreutils
  - dconf-editor
  - tmux
  - fzf
  - xclip
  - screenkey
  - ripgrep
  - zsh
  - zsh-history-substring-search
  - zsh-theme-powerlevel10k
  - jenv
  - nfs-utils
  - cifs-utils
  - gnome-keyring
  - make
  - inkscape
  - clojure
  - go

dmg_apps:
  - { name: "Logseq", url: https://github.com/logseq/logseq }
  - { name: "Obsidian", url: https://github.com/obsidianmd/obsidian-releases }

aur_packages:
  - 1password
  - appimagelauncher-git
  - auracle-git
  - brave-bin
  - insomnia-bin
  - logseq-desktop
  - neovim-git
  - nerd-fonts-noto-sans-mono
  - nvm
  - otf-san-francisco
  - plymouth-git
  - python-elgato-streamdeck
  - python-pynput
  - slack-desktop
  - streamdeck-ui
  - teams-insiders
  - todoist-appimage
  - obsidian-appimage

projects:
  - org: swatchltd
    repo: git@github.com:Swatchltd/swa-digital-catalog.git
    bare: yes
  - org: quandoo
    repo: git@gitlab.com:quandoo-dev/portal-group/portal.git
    bare: yes
  - org: quandoo
    repo: git@gitlab.com:quandoo-dev/portal-group/portal_api.git
