---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: git@github.com:clempat/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/workspace/perso/dotfiles
dotfiles_repo_version: main
dotfiles_folders:
  - ~/.local/share
  - ~/.config
  - ~/.config/gtk-3.0
  - ~/.config/gtk-2.0
  - ~/.local/bin
dotfiles_files:
  - .zprofile
  - .zshrc
  - .osx
  - .bashrc
  - .p10k.zsh
  - .profile
  - .tmux.conf
  - .tmux-cht-command
  - .tmux-cht-languages
  - .config/nvim/lua/custom
  - .local/bin/tmux-sessionizer
  - .gitconfig
  - .config/systemd
  - .config/kitty
  - .config/i3
  - .config/i3status
  - .config/picom
  - .config/rofi
  - .config/dunst
  - .config/fontconfig
  - .local/share/rofi
  - .config/gtk-3.0/settings.ini
  - .config/gtk-2.0/settings.ini
  - .config/yabai

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: tldr
  - name: typescript
  - name: pnpm
  - name: yarn
  - name: prettier
  - name: eslint_d
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

powerline_fonts:
  - RobotoMono

pacman_packages:
  - i3-gaps
  - bluez
  - bluez-utils
  - blueman
  - xorg-server
  - xorg-apps
  - xorg-xinit
  - lightdm
  - lightdm-gtk-greeter
  - ttf-ubuntu-font-family
  - ttf-dejavu
  - ttf-freefont
  - pavucontrol
  - moreutils
  - dconf-editor
  - tmux
  - fzf
  - xclip
  - screenkey
  - ripgrep
  - zsh
  - zsh-history-substring-search
  - zsh-theme-powerlevel10k
  - jenv
  - nfs-utils
  - cifs-utils
  - gnome-keyring
  - make
  - inkscape
  - clojure
  - go
  - alacritty

aur_packages:
  - libvterm-0.1 # Needed for neovim
  - 1password
  - appimagelauncher-git
  - auracle-git
  - brave-bin
  - insomnia-bin
  - logseq-desktop
  - neovim-git
  - nerd-fonts-noto-sans-mono
  - nvm
  - otf-san-francisco-mono
  - plymouth-git
  - python-elgato-streamdeck
  - python-pynput
  - slack-desktop
  - streamdeck-ui
  - teams-insiders
  - todoist-appimage
  - obsidian-appimage

projects:
  []
  #  - org: swatchltd
  #    repo: git@github.com:Swatchltd/swa-digital-catalog.git
  #    bare: yes
  #  - org: quandoo
  #    repo: git@gitlab.com:quandoo-dev/portal-group/portal.git
  #    bare: yes
  #  - org: quandoo
  #    repo: git@gitlab.com:quandoo-dev/portal-group/portal_api.git
