---
- hosts: all

  vars_files:
    - config.yml

  pre_tasks:
    - import_tasks: tasks/requirements.yml
      tags: ["dotfiles"]

  roles:
    - role: elliotweiser.osx-command-line-tools
      when: ansible_facts['os_family'] == 'Darwin'
    - role: geerlingguy.mac.homebrew
      when: ansible_facts['os_family'] == 'Darwin'
      tags: ["homebrew"]
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
    - role: geerlingguy.mac.mas
      when: ansible_facts['os_family'] == 'Darwin' and mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      when: ansible_facts['os_family'] == 'Darwin' and configure_dock
      tags: ["dock"]

  tasks:
    - name: Check the OS
      debug:
        var: ansible_facts['os_family']

    - import_tasks: tasks/i3.yml
      when: ansible_facts['os_family'] != 'Darwin'
      tags: ["i3"]

    - import_tasks: tasks/sudoers.yml
      when: ansible_facts['os_family'] == 'Darwin' and configure_sudoers
      tags: ["sudoers"]

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ["terminal"]

    - import_tasks: tasks/osx.yml
      when: ansible_facts['os_family'] == 'Darwin' and configure_osx
      tags: ["osx"]

    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]

    - import_tasks: tasks/neovim.yml
      tags: ["neovim"]

    - import_tasks: tasks/git.yml
      tags: ["git"]

    - import_tasks: tasks/projects.yml
      tags: ["projects"]

    - import_tasks: tasks/zsh.yml
      tags: ["zsh"]

    - import_tasks: tasks/fonts.yml
      tags: ["fonts"]

    - include_tasks:
        file: tasks/dmg.yml
        apply:
          tags: ["dmg"]
      when: ansible_facts['os_family'] == 'Darwin' and dmg_apps
      tags: ["dmg"]
      loop: "{{ dmg_apps }}"

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ["post"]
