---
- hosts: all

  vars_files:
    - config.yml

  pre_tasks:
    - import_tasks: tasks/requirements.yml
      tags: ["dotfiles"]

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
    - role: luizgavalda.aur
      when: ansible_facts['os_family'] == 'Archlinux'
      tags: ["aur"]

  tasks:
    - name: Check the OS
      debug:
        var: ansible_facts['os_family']

    - import_tasks: tasks/yay.yml
      tags: ["yay"]

    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]

    - import_tasks: tasks/neovim.yml
      tags: ["neovim"]

    - import_tasks: tasks/git.yml
      tags: ["git"]

    - import_tasks: tasks/zsh.yml
      tags: ["zsh"]

    - import_tasks: tasks/fonts.yml
      tags: ["fonts"]

    - include_tasks:
        file: tasks/projects.yml
        apply:
          tags: ["projects"]
      tags: ["projects"]
      loop: "{{ projects }}"

    - include_tasks:
        file: tasks/gtk-icons.yml
        apply:
          tags: ["gtk-icons"]
      tags: ["gtk-icons"]
      when: false # could not having working. doing it manualy
      loop:
        - https://github.com/bikass/kora.git

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ["post"]
