---
- name: "Download Icons repository"
  git:
    repo: "{{item}}"
    dest: "/tmp/{{item | basename }}"
  register: unarchive
- name: "Clean the folder"
  block:
    - command: "find /tmp/{{item | basename }} -maxdepth 1 -type f -delete"
    - command: "rm -rf /tmp/{{item|basename}}/.git"
- name: "Install Icons"
  command: "cp -r /tmp/{{item | basename}}/* /usr/share/icons/"
  become: true
