---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Check .osx exists
  stat:
    path: "~/.osx"
  register: osx
- name: Update .osx permissions
  file:
    state: touch
    path: "~/.osx"
    mode: a+x
  when: osx.stat.exists
- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  changed_when: false
  when: osx.stat.exists
