---
- name: "Clone {{ item.org | default('Personal') }} Projects"
  tags: "[{{ item.org | default('perso') }}]"
  git:
    repo: "{{ item.repo | default(item) }}"
    dest: "{{ lookup('env', 'HOME') | default('~') }}/workspace/{{ item.org | default('perso') }}/{{ item.repo | default(item) | basename | replace('.git', '')}}/{%- if 'bare' in item and item.bare -%}.bare/{%- endif -%}"
    key_file: "{{ lookup('env', 'HOME') | default('~') }}/.ssh/ansible"
    bare: "{{ item.bare | default('no') }}"
- name: Add .git if .bare
  copy:
    content: "gitdir: ./.bare"
    dest: "{{ lookup('env', 'HOME') | default('~') }}/workspace/{{ item.org | default('perso') }}/{{ item.repo | default(item) | basename | replace('.git', '')}}/.git"
  when: "'bare' in item and item.bare"
