---
# Install for mac
- name: Install terminal theme on Mac
  when: ansible_facts['os_family'] == 'Darwin'
  block:
    - name: Get current Terminal profile.
      command: defaults read com.apple.terminal 'Default Window Settings'
      register: terminal_theme
      changed_when: false
      check_mode: false

    - name: Ensure custom Terminal profile is added.
      copy:
        src: files/terminal/Dracula.terminal
        dest: /tmp/Dracula.terminal
      changed_when: false
      when: "Dracula' not in terminal_theme.stdout"

    - name: Ensure custom Terminal profile is added.
      command: open /tmp/Dracula.terminal
      changed_when: false
      when: "'Dracula' not in terminal_theme.stdout"

    # TODO: This doesn't work in Yosemite. Consider a different solution?
    - name: Ensure custom Terminal profile is set as default.
      command: "{{ item }}"
      with_items:
        - defaults write com.apple.terminal 'Default Window Settings' -string Dracula
        - defaults write com.apple.terminal 'Startup Window Settings' -string Dracula
      changed_when: false
      when: "'Dracula' not in terminal_theme.stdout"
# Install for Linux
- name: Install terminal theme on Linux
  when: ansible_facts['os_family'] != 'Darwin'
  block:
    - name: Get the theme repository
      git:
        depth: 1
        repo: https://github.com/dracula/gnome-terminal
        dest: "{{ lookup('env', 'HOME') | default('~') }}/workspace/libs/dracula/gnome-terminal"

    - name: Add permissions
      file:
        path: "{{ lookup('env', 'HOME') | default('~') }}/workspace/libs/dracula/gnome-terminal/install.sh"
        mode: "a+x"

    - name: Install Theme for Gnome terminal
      shell: "{{ lookup('env', 'HOME') | default('~') }}/workspace/libs/dracula/gnome-terminal/install.sh -s Dracula -p Dracula --install-dircolors"
